version: "3.9"
services:
  web:
    build: .
    container_name: shadowtalk_web
    env_file: .env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
    command: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:5000

  redis:
    image: redis:alpine
    container_name: shadowtalk_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: shadowtalk_nginx
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
